Update patch set 1
Patch Set 1:

Another compilation error: https://gist.github.com/bgcngm/60fb401d643d932832f8d5c99c3fbeb0
And for this one I don't what flag is causing it.

Patch-set: 1