Update patch set 1
Patch Set 1: -Verified

With the only applying the following picks I get an error:
eee37f293 (HEAD) post_proc: Mark unused parameters with (void)
a4e2e254a hal: Remove redundant LOCAL_C_INCLUDES
227a711c7 hal: Formatting
67055fd27 post_proc: Handle unused asphere function parameters
b552683a0 post_proc: Remove unused label
54dd974f8 Bypass compilation errors due to compiler upgrade

---
hardware/qcom/audio-caf/msm8952/hal/audio_hw.c:2005:13: error: unused function 'out_snd_mon_cb' [-Werror,-Wunused-function]
static void out_snd_mon_cb(void * stream, struct str_parms * parms)
            ^
hardware/qcom/audio-caf/msm8952/hal/audio_hw.c:2773:13: error: unused function 'in_snd_mon_cb' [-Werror,-Wunused-function]
static void in_snd_mon_cb(void * stream, struct str_parms * parms)
            ^
hardware/qcom/audio-caf/msm8952/hal/audio_hw.c:3952:13: error: unused function 'adev_snd_mon_cb' [-Werror,-Wunused-function]
static void adev_snd_mon_cb(void *cookie, struct str_parms *parms)

This isn't the case when using this pick.
Do I miss something?

Patch-set: 1
Reviewer: Quallenauge <8752@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0