audiopolicy: Remove old raw pointer references
Fix compile from changes in frameworks/av:

"DO NOT MERGE: audiopolicy: Remove raw pointer references to AudioMix"

error: member reference type 'wp<android::AudioPolicyMix>' is not a pointer;

Change-Id: Ia5794abb757c77ff63b453906b756deb07ca305f