Audio: dts_eagle.c: fixed some errors
error: passing 'const struct stream_out *' to parameter of type 'struct stream_out *' discards qualifiers
+ add the missing qualifier 'const'

error: format specifies type 'unsigned long' but the argument has type 'unsigned int'
+ change the printed data type to size_t

Change-Id: I563dc458be69305605d8786cdf20d83b099374f6
Signed-off-by: gesangtome <gesangtome@foxmail.com>